### PR TITLE
Parse 'strict' and 'lax' keywords at the start of a statement

### LINKED ISSUE #7: Add `lax` and `strict` mode keywords
SQL JSONPath has an optional mode keyword of `lax` and `strict`. They go at the very start of an expression:

`strict $ ...`

`lax $ ...`

`strict` means the expressed paths must exist in the type they are expected to be. They should throw an error if not there.

Given:

```json
{
  "first": "Matt",
  "last": "Bison"
}
```

This should throw an error: `strict $.full`

Whereas this should simply be undefined: `lax $.full`

`lax` is the default mode if none is specified.

### PR DESCRIPTION
**Pull request by mattbishop**
Resolves #7

### CODE REVIEW

**Comment by mattbishop** [comment]
@JeffML want to review?

**Comment by JeffML** [comment]
Sure, I'll take a look soonish.

**Comment by JeffML** [comment]
Looks like the mode is captured ok.  Should **lax** be the default?  I see that if mode is unspecified it is "undefined", but I think that implies **lax**.

There's the issue of nesting/unnesting arrays in **lax** mode (6.3, table 28). I don't know what operator subrules (if any) require conditionals to handle those cases.

Error handling for non-null data in strict mode is something you might want to write an issue about. I haven't given it any thought.

**Comment by mattbishop** [comment]
`lax` is the default, according to the spec. It makes sense to set mode to always be lax if not set, I will add that in.

As for interpreting the meaning of strict, that is a runtime concern, not a parser concern. When one applies a parsed JSONPath statement to a JSON object, these modes kick in.

**Comment by JeffML** [comment]
Hmmm...I still think the wrapping/unwrapping of arrays might be handled at
the parser level in lax mode, but it does make for a more complicated
parser.

**Comment by mattbishop** [comment]
I added 'lax' as the default mode if none is specified.

**Comment by mattbishop** [comment]
About the lax array wrapping/unwrapping, how would that affect the statement parser's CST output? For instance:

`lax $.track.segments.location`

Which of those parts is an array? We don't know, so the CST would have to have some kind of OR declaration to indicate either property accessor or array[*] accessor for every path part. That might be a bit heavy?

Perhaps the search function could pick up the load and convert the property to an array handler if it discovers the property type is actually an array instead of object. Something like:

```js
if (lhsElement.property) {
  const property = obj[lhsElement.property]
  if (Array.isArray(property)) {
    if (ctx.mode === "strict") {
      throw new Error("strict mode won't unwrap arrays for you")
    }
    // switch to property[*] handling
  } else {
    // handle as a single property 
  }
}
```

**Comment by JeffML** [comment]
Sorry, didn't see your previous comments until just now.

**Pull request merged**
